openapi: 3.0.0
info:
  title: Simple Inventory API
  description: This is a simple API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/module-service
  description: SwaggerHub API Auto Mocking
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /healthcheck:
    get:
      tags: []
      summary: healthcheck
      description: Standard server healthcheck
      operationId: healthcheck
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /organizations/{organization_id}/notebooks/{notebook_id}/modules:
    get:
      tags: []
      summary: get list of modules
      description: get list of modules for given organization {organization_id} and given notebook {notebook_id}
      operationId: get_modules
      parameters:
        - name: organization_id
          in: path
          required: true
          schema:
            type: string
        - name: notebook_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Modules"
        "500":
          description: Internal Server Error
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    Modules:
      type: object
      properties:
        modules:
          type: array
          items:
            type: string
