name: Build Test and push
on: [push]
env:
  IMAGE_NAME: project_interface
  REPO_NAME: ilia008
 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build docker
      run: |
        docker build . -t tag1
    - name: run docker
      run: |
        docker run -d -p 8080:8080 tag1 && \
          docker ps && sleep 5

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Tag image
      run: | 
          docker tag tag1 ilia008/project_interface
  
    - name: Push image to docker hub Container Registry
      run: | 
          docker push ilia008/project_interface

    - name: exper
      run : |
          aws --version

    - name: AWS Login
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
