name: Build and Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build docker
      run: |
        docker build . --platform linux/amd64 -t 314146339425.dkr.ecr.eu-central-1.amazonaws.com/project/web_interface

    - name: run docker
      run: |
        docker run -d -p 8080:8080 314146339425.dkr.ecr.eu-central-1.amazonaws.com/project/web_interface && \
          docker ps && sleep 5

    - name: AWS Configure Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-central-1
        role-to-assume: arn:aws:iam::314146339425:role/PushDockerImageECR
        role-session-name: PushDockerImageECR

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: true
        skip-logout: false
        
    - name: Push Docker Image
      run : |
        docker push 314146339425.dkr.ecr.eu-central-1.amazonaws.com/project/web_interface

  update_ECS:
    needs: build_and_push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    
    steps:
    - name: AWS Configure Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-central-1
        role-to-assume: arn:aws:iam::314146339425:role/UpdateECSTask
        role-session-name: UpdateECSTask

    - name: Stop All Running Tasks
      run: |
        TASKS=$(aws ecs list-tasks --cluster BigTuna --family module-service --query "taskArns[]" --output text)
        for TASK in $TASKS; do
          aws ecs stop-task --cluster BigTuna --task $TASK --reason "Stopping all tasks for cleanup"
        done

    - name: Update ECS
      run: |
        aws ecs update-service --cluster BigTuna --service module-service --force-new-deployment
