name: Build Test and push
on: [push]
env:
  IMAGE_NAME: project_interface
  REPO_NAME: ilia008
 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build docker
      run: |
        docker build . -t tag1
    - name: run docker
      run: |
        docker run -d -p 8080:8080 tag1 && \
          docker ps && sleep 5

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Tag image
      run: | 
          docker tag tag1 ilia008/project_interface
  
    - name: Push image to docker hub Container Registry
      run: | 
          docker push ilia008/project_interface

    - name: exper
      run : |
          aws --version

    - name: AWS Login
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ASIAUSJEUXJQZAJLXGUN
        aws-secret-access-key: w9M+ZwTE431z+QL1UUzLhQ+YV1zFnlq5Vn7ikp+A
        aws-region: eu-north-1

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 314146339425.dkr.ecr.eu-north-1.amazonaws.com
        
    - name: exper
      run : |
        docker tag ilia008/project_interface 314146339425.dkr.ecr.eu-north-1.amazonaws.com/project/web_interface
        docker push 314146339425.dkr.ecr.eu-north-1.amazonaws.com/project/web_interface
