name: Build Test and push
on: [push]
env:
  IMAGE_NAME: project_interface
  REPO_NAME: ilia008
 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build docker
      run: |
        docker build . -t ilia008/project_interface
    - name: run docker
      run: |
        docker run -d -p 8080:8080 ilia008/project_interface:latest && \
          docker ps && sleep 5

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push image to docker hub Container Registry
      run: | 
          docker push ilia008/project_interface
